app = "nats-server"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[mounts]
  source = "nats_data"
  destination = "/data"

[experimental]
  cmd = ["-js", "-sd", "/data"]

[[services]]
  protocol = "tcp"
  internal_port = 4222

  [[services.ports]]
    port = 4222
    handlers = []

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
