# fly.toml app configuration file generated for nats-server-summer-tree-8296 on 2026-01-30T14:21:18-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nats-server-summer-tree-8296'
primary_region = 'gru'

[experimental]
  cmd = ['-js', '-sd', '/data', '-m', '8222','-a','::']

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'nats_data'
  destination = '/data'

#[[services]]
#  protocol = 'tcp'
#  internal_port = 4222

#  [[services.ports]]
#    port = 4222

[[services]]
  protocol = 'tcp'
  internal_port = 8222

  [[services.ports]]
    port = 8222
    handlers = ['http','tls']

[[vm]]
  memory = '512mb'
  cpus = 1
  memory_mb = 512
